version: "3.9"

services:
  api:
    image: tahaidrissi05/taskmanagerapi:latest
    networks:
      - public
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=public"
        - "traefik.http.routers.api.rule=Host(`admin.tahaidrissi.digital`)"
        - "traefik.http.routers.api.entrypoints=websecure"
        - "traefik.http.routers.api.tls.certresolver=default"
        - "traefik.http.services.api.loadbalancer.server.port=8000"

networks:
  public:
    external: true
